### ISSUE TITLE
Barplot fails to makes bars when only one site needs to be plotted

### ISSUE THREAD

**Issue by KeelyDulmage** [CBIIT-CGBB/OmicCircos2#2]
This issue appears in both 1.43.0 of OmicCircos on Bioconductor and the github dev version OmicCircos2 0.2.0. 

Following the example from the previous issue, here is a barplot with several sites that works:

```{r}
data("UCSC.hg19.chr");
data("UCSC.hg19");
dat <- read.table("01for_polygons.txt", header=T);
set.seed(1234);
dat$some_val <- sample(1:300, size = nrow(dat));
cols <- rainbow(nrow(dat), alpha=0.4);

par(mar=c(2, 2, 2, 2));
plot(c(1,800), c(1,800), type="n", axes=F, xlab="", ylab="", main="");

circos(R=385, cir=UCSC.hg19, mapping=UCSC.hg19.chr, type="chr.label.h", cex=1.3);
circos(R=350, cir=UCSC.hg19, mapping=UCSC.hg19.chr, type="chr.scale", lwd=0.001, cex=0.3);
circos(R=350, cir=UCSC.hg19, mapping=UCSC.hg19.chr, type="chr", W=10);
circos(R = 250, cir=UCSC.hg19, mapping=dat, W=90,type="b", lwd=2, col=cols, col.v = 7, scale = T)
```

And if I reduce it to a single site, no barplots appear on the figure:

```{r}
par(mar=c(2, 2, 2, 2));
plot(c(1,800), c(1,800), type="n", axes=F, xlab="", ylab="", main="");

circos(R=385, cir=UCSC.hg19, mapping=UCSC.hg19.chr, type="chr.label.h", cex=1.3);
circos(R=350, cir=UCSC.hg19, mapping=UCSC.hg19.chr, type="chr.scale", lwd=0.001, cex=0.3);
circos(R=350, cir=UCSC.hg19, mapping=UCSC.hg19.chr, type="chr", W=10);
circos(R = 250, cir=UCSC.hg19, mapping=dat[1,,drop = F], W=90,type="b", lwd=2, col=cols, col.v = 7, scale = T)
```

I think this may have something to do with the scale, as all the numbers on the scale appear to be the max value.

This is a critical issue for us as we are trying to reduce the number of sites that are detected (fewer = better).

**Comment by CBIIT-CGBB** [comment]
library(OmicCircos2)
options(stringsAsFactors = F);

data("UCSC.hg19.chr");
data("UCSC.hg19");
dat <- read.table("01for_polygons.txt", header=T);
set.seed(1234);
dat$some_val <- sample(1:300, size = nrow(dat));

## sort chromosome and position for the color(s)
dat.n     <- dat[,c(1:2)];
dat.n[,1] <- gsub("chr", "", dat.n[,1]);
dat.n[,1] <- as.numeric(dat.n[,1]);
dat.i     <- with(dat.n, order(chr1, start1))
dat       <- dat[dat.i,];

cols    <- rep("white", nrow(dat));
cols[4] <- "black";

pdf("20230105.pdf", 6, 6);
par(mar=c(2, 2, 2, 2));
plot(c(1,800), c(1,800), type="n", axes=F, xlab="", ylab="", main="");

circos(R=400, cir=UCSC.hg19, mapping=UCSC.hg19.chr, type="chr.label.h", cex=1);
circos(R=350, cir=UCSC.hg19, mapping=UCSC.hg19.chr, type="chr.scale", lwd=0.001, cex=0.3);
circos(R=350, cir=UCSC.hg19, mapping=UCSC.hg19.chr, type="chr", W=10);
## The length was based on the sample distribution.
circos(R = 250, cir=UCSC.hg19, mapping=dat, W=90, type="b", lwd=2, col=cols, col.v = 7)
## if you ignore the value (length), you could use "b3". 
circos(R = 150, cir=UCSC.hg19, mapping=dat[4,], W=90, type="b3", lwd=2, col="black", col.v = 7)

dev.off();

**Comment by KeelyDulmage** [comment]
Ah, I think the b3 option will work, I'll just make that conditional for when there's only one site, we really need the barchart ("b" option) for multiple sites.  Thank you for your quick response!
